name: DCO Check
on: [pull_request]

jobs:
  dco_check_job:
    runs-on: ubuntu-latest
    name: DCO Check
    # Skip DCO check for bot-generated sync PRs
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'fbchef_sync_bot') }}
    steps:
    - name: Get PR Commits
      uses: tim-actions/get-pr-commits@master
      id: 'get-pr-commits'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: DCO Check
      uses: tim-actions/dco@master
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
